# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/dev/nahyun/nest-compiler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/dev/nahyun/nest-compiler/build18

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"dev\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	cd /root/dev/nahyun/nest-compiler/build18 && $(CMAKE_COMMAND) -E cmake_progress_start /root/dev/nahyun/nest-compiler/build18/CMakeFiles /root/dev/nahyun/nest-compiler/build18/vta/bundles/Resnet18Test/CMakeFiles/progress.marks
	cd /root/dev/nahyun/nest-compiler/build18 && $(MAKE) -f CMakeFiles/Makefile2 vta/bundles/Resnet18Test/all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/dev/nahyun/nest-compiler/build18/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /root/dev/nahyun/nest-compiler/build18 && $(MAKE) -f CMakeFiles/Makefile2 vta/bundles/Resnet18Test/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /root/dev/nahyun/nest-compiler/build18 && $(MAKE) -f CMakeFiles/Makefile2 vta/bundles/Resnet18Test/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /root/dev/nahyun/nest-compiler/build18 && $(MAKE) -f CMakeFiles/Makefile2 vta/bundles/Resnet18Test/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /root/dev/nahyun/nest-compiler/build18 && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
vta/bundles/Resnet18Test/CMakeFiles/vtaMxnetResnet18Bundle.dir/rule:
	cd /root/dev/nahyun/nest-compiler/build18 && $(MAKE) -f CMakeFiles/Makefile2 vta/bundles/Resnet18Test/CMakeFiles/vtaMxnetResnet18Bundle.dir/rule
.PHONY : vta/bundles/Resnet18Test/CMakeFiles/vtaMxnetResnet18Bundle.dir/rule

# Convenience name for target.
vtaMxnetResnet18Bundle: vta/bundles/Resnet18Test/CMakeFiles/vtaMxnetResnet18Bundle.dir/rule

.PHONY : vtaMxnetResnet18Bundle

# fast build rule for target.
vtaMxnetResnet18Bundle/fast:
	cd /root/dev/nahyun/nest-compiler/build18 && $(MAKE) -f vta/bundles/Resnet18Test/CMakeFiles/vtaMxnetResnet18Bundle.dir/build.make vta/bundles/Resnet18Test/CMakeFiles/vtaMxnetResnet18Bundle.dir/build
.PHONY : vtaMxnetResnet18Bundle/fast

# Convenience name for target.
vta/bundles/Resnet18Test/CMakeFiles/vtaMxnetResnet18BundleNet.dir/rule:
	cd /root/dev/nahyun/nest-compiler/build18 && $(MAKE) -f CMakeFiles/Makefile2 vta/bundles/Resnet18Test/CMakeFiles/vtaMxnetResnet18BundleNet.dir/rule
.PHONY : vta/bundles/Resnet18Test/CMakeFiles/vtaMxnetResnet18BundleNet.dir/rule

# Convenience name for target.
vtaMxnetResnet18BundleNet: vta/bundles/Resnet18Test/CMakeFiles/vtaMxnetResnet18BundleNet.dir/rule

.PHONY : vtaMxnetResnet18BundleNet

# fast build rule for target.
vtaMxnetResnet18BundleNet/fast:
	cd /root/dev/nahyun/nest-compiler/build18 && $(MAKE) -f vta/bundles/Resnet18Test/CMakeFiles/vtaMxnetResnet18BundleNet.dir/build.make vta/bundles/Resnet18Test/CMakeFiles/vtaMxnetResnet18BundleNet.dir/build
.PHONY : vtaMxnetResnet18BundleNet/fast

# Convenience name for target.
vta/bundles/Resnet18Test/CMakeFiles/vtaMxnetResnet18BundleONNX.dir/rule:
	cd /root/dev/nahyun/nest-compiler/build18 && $(MAKE) -f CMakeFiles/Makefile2 vta/bundles/Resnet18Test/CMakeFiles/vtaMxnetResnet18BundleONNX.dir/rule
.PHONY : vta/bundles/Resnet18Test/CMakeFiles/vtaMxnetResnet18BundleONNX.dir/rule

# Convenience name for target.
vtaMxnetResnet18BundleONNX: vta/bundles/Resnet18Test/CMakeFiles/vtaMxnetResnet18BundleONNX.dir/rule

.PHONY : vtaMxnetResnet18BundleONNX

# fast build rule for target.
vtaMxnetResnet18BundleONNX/fast:
	cd /root/dev/nahyun/nest-compiler/build18 && $(MAKE) -f vta/bundles/Resnet18Test/CMakeFiles/vtaMxnetResnet18BundleONNX.dir/build.make vta/bundles/Resnet18Test/CMakeFiles/vtaMxnetResnet18BundleONNX.dir/build
.PHONY : vtaMxnetResnet18BundleONNX/fast

mxnet_exported_resnet18.o: mxnet_exported_resnet18.cpp.o

.PHONY : mxnet_exported_resnet18.o

# target to build an object file
mxnet_exported_resnet18.cpp.o:
	cd /root/dev/nahyun/nest-compiler/build18 && $(MAKE) -f vta/bundles/Resnet18Test/CMakeFiles/vtaMxnetResnet18Bundle.dir/build.make vta/bundles/Resnet18Test/CMakeFiles/vtaMxnetResnet18Bundle.dir/mxnet_exported_resnet18.cpp.o
.PHONY : mxnet_exported_resnet18.cpp.o

mxnet_exported_resnet18.i: mxnet_exported_resnet18.cpp.i

.PHONY : mxnet_exported_resnet18.i

# target to preprocess a source file
mxnet_exported_resnet18.cpp.i:
	cd /root/dev/nahyun/nest-compiler/build18 && $(MAKE) -f vta/bundles/Resnet18Test/CMakeFiles/vtaMxnetResnet18Bundle.dir/build.make vta/bundles/Resnet18Test/CMakeFiles/vtaMxnetResnet18Bundle.dir/mxnet_exported_resnet18.cpp.i
.PHONY : mxnet_exported_resnet18.cpp.i

mxnet_exported_resnet18.s: mxnet_exported_resnet18.cpp.s

.PHONY : mxnet_exported_resnet18.s

# target to generate assembly for a file
mxnet_exported_resnet18.cpp.s:
	cd /root/dev/nahyun/nest-compiler/build18 && $(MAKE) -f vta/bundles/Resnet18Test/CMakeFiles/vtaMxnetResnet18Bundle.dir/build.make vta/bundles/Resnet18Test/CMakeFiles/vtaMxnetResnet18Bundle.dir/mxnet_exported_resnet18.cpp.s
.PHONY : mxnet_exported_resnet18.cpp.s

mxnet_exported_resnet18BundleMain.o: mxnet_exported_resnet18BundleMain.cpp.o

.PHONY : mxnet_exported_resnet18BundleMain.o

# target to build an object file
mxnet_exported_resnet18BundleMain.cpp.o:
	cd /root/dev/nahyun/nest-compiler/build18 && $(MAKE) -f vta/bundles/Resnet18Test/CMakeFiles/vtaMxnetResnet18Bundle.dir/build.make vta/bundles/Resnet18Test/CMakeFiles/vtaMxnetResnet18Bundle.dir/mxnet_exported_resnet18BundleMain.cpp.o
.PHONY : mxnet_exported_resnet18BundleMain.cpp.o

mxnet_exported_resnet18BundleMain.i: mxnet_exported_resnet18BundleMain.cpp.i

.PHONY : mxnet_exported_resnet18BundleMain.i

# target to preprocess a source file
mxnet_exported_resnet18BundleMain.cpp.i:
	cd /root/dev/nahyun/nest-compiler/build18 && $(MAKE) -f vta/bundles/Resnet18Test/CMakeFiles/vtaMxnetResnet18Bundle.dir/build.make vta/bundles/Resnet18Test/CMakeFiles/vtaMxnetResnet18Bundle.dir/mxnet_exported_resnet18BundleMain.cpp.i
.PHONY : mxnet_exported_resnet18BundleMain.cpp.i

mxnet_exported_resnet18BundleMain.s: mxnet_exported_resnet18BundleMain.cpp.s

.PHONY : mxnet_exported_resnet18BundleMain.s

# target to generate assembly for a file
mxnet_exported_resnet18BundleMain.cpp.s:
	cd /root/dev/nahyun/nest-compiler/build18 && $(MAKE) -f vta/bundles/Resnet18Test/CMakeFiles/vtaMxnetResnet18Bundle.dir/build.make vta/bundles/Resnet18Test/CMakeFiles/vtaMxnetResnet18Bundle.dir/mxnet_exported_resnet18BundleMain.cpp.s
.PHONY : mxnet_exported_resnet18BundleMain.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... vtaMxnetResnet18Bundle"
	@echo "... vtaMxnetResnet18BundleNet"
	@echo "... vtaMxnetResnet18BundleONNX"
	@echo "... mxnet_exported_resnet18.o"
	@echo "... mxnet_exported_resnet18.i"
	@echo "... mxnet_exported_resnet18.s"
	@echo "... mxnet_exported_resnet18BundleMain.o"
	@echo "... mxnet_exported_resnet18BundleMain.i"
	@echo "... mxnet_exported_resnet18BundleMain.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /root/dev/nahyun/nest-compiler/build18 && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

